version: '2.3'
services:
  # Base images
  ros_melodic_base:
    build: 
      context: ./ros_melodic
      dockerfile: Dockerfile
    image: airobots_docker:ros_melodic
    container_name: ros_melodic

  ros_noetic_base:
    build: 
      context: ./ros_noetic
      dockerfile: Dockerfile
    image: airobots_docker:ros_noetic
    container_name: ros_noetic

  ros_foxy_base:
    build: 
      context: ./ros_foxy
      dockerfile: Dockerfile
    image: airobots_docker:ros_foxy
    container_name: ros_foxy

  # Application
  ros_slam:
    build:
      context: ./ros_slam
      dockerfile: Dockerfile     
    depends_on: [ros_melodic_base]
    image: airobots_docker:ros_slam
    container_name: ros_slam
    runtime: nvidia
    user: aiRobots
    privileged: true
    volumes:
      - ~/aiRobots/aiRobots_AMMR:/home/aiRobots/aiRobots/aiRobots_AMMR/
      - ~/aiRobots/SLAM:/home/aiRobots/aiRobots/SLAM/
      - ~/aiRobots/Datasets:/home/aiRobots/aiRobots/Datasets/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      # - "ROS_IP=192.168.50.248"
      # - "ROS_MASTER_URI=http://192.168.50.149:11311"
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "XAUTHORITY=/tmp/.docker.xauth"

  humanoid:
    build:
      context: ./humanoid
      dockerfile: Dockerfile     
    depends_on: [ros_melodic_base]
    image: airobots_docker:humanoid
    container_name: humanoid
    runtime: nvidia
    user: aiRobots
    privileged: true
    network_mode: "host"
    volumes:
      - ~/aiRobots/Humanoid:/home/aiRobots/aiRobots/Humanoid/:rw
      - ~/aiRobots/Datasets:/home/aiRobots/aiRobots/Datasets/:rw
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      # - "ROS_IP=192.168.50.248"
      # - "ROS_MASTER_URI=http://192.168.50.149:11311"
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "XAUTHORITY=/tmp/.docker.xauth"

  Joy:
    build:
      context: ./Joy
      dockerfile: Dockerfile
    depends_on: [ros_noetic_base]
    image: airobots_docker:Joy
    container_name: Joy
    runtime: nvidia
    user: aiRobots
    privileged: true
    volumes:
      - ~/aiRobots:/home/aiRobots/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "XAUTHORITY=/tmp/.docker.xauth"

  aiRobots_AMMR:
    build:
      context: ./AMMR
      dockerfile: Dockerfile     
    depends_on: [ros_melodic_base]
    image: airobots_docker:aiRobots_AMMR
    container_name: aiRobots_AMMR
    network_mode: "host"
    user: aiRobots
    privileged: true
    volumes:
      - ~/aiRobots/aiRobots_AMMR:/home/aiRobots/aiRobots/aiRobots_AMMR/
      - ~/aiRobots/SLAM:/home/aiRobots/aiRobots/SLAM/
      - ~/aiRobots/Datasets:/home/aiRobots/aiRobots/Datasets/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev:/dev
      - /run/udev:/run/udev:ro
    environment:
      # - "ROS_IP=192.168.50.248"
      # - "ROS_MASTER_URI=http://192.168.50.149:11311"
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "XAUTHORITY=/tmp/.docker.xauth"

  pybullet_stable_baselines:
    build:
      context: ./pybullet_stable_baselines
      dockerfile: Dockerfile     
    image: airobots_docker:pybullet_stable_baselines
    container_name: pybullet_stable_baselines
    # runtime: nvidia
    user: aiRobots
    privileged: true
    volumes:
      - ~/aiRobots/Pybullet_Thesis:/home/aiRobots/aiRobots/Pybullet_Thesis/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - /dev:/devl
      - /run/udev:/run/udev:ro
    environment:
      # - "ROS_IP=192.168.50.248"
      # - "ROS_MASTER_URI=http://192.168.50.149:11311"
      - "DISPLAY=$DISPLAY"
      - "QT_X11_NO_MITSHM=1"
      - "XAUTHORITY=/tmp/.docker.xauth"